title = "CLI .NET decompiler"
description = "Extract the source code (.cs) of a .NET binary"
tags = ["rev", ".NET"]

[[data]]
description = "Usage: ilspy example.exe"
language = "bash"
command = """function ilspy(){
	sudo docker run --rm -v `pwd`:/samples cincan/ilspy /samples/"$1" > `basename $1`.cs
	echo `basename $1`.cs
}"""
